
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 27 15:18:17 CET 2019
//----------------------------------------------------

package compilateurYal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 33;
  public static final int TANTQUE = 30;
  public static final int CRO_OUV = 14;
  public static final int EGAL = 11;
  public static final int REPETER = 31;
  public static final int SI = 26;
  public static final int BOOLEEN = 10;
  public static final int VIRGULE = 6;
  public static final int FIN = 4;
  public static final int LIRE = 8;
  public static final int LONGUEUR = 36;
  public static final int OU = 25;
  public static final int INF = 21;
  public static final int CRO_FER = 15;
  public static final int NON = 23;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int PAR_OUV = 12;
  public static final int error = 1;
  public static final int RETOURNE = 34;
  public static final int MOINS = 17;
  public static final int ET = 24;
  public static final int IDF = 37;
  public static final int SINON = 28;
  public static final int ALORS = 27;
  public static final int POINT = 35;
  public static final int CSTENTIERE = 38;
  public static final int PROGRAMME = 2;
  public static final int PAR_FER = 13;
  public static final int POINTVIRGULE = 5;
  public static final int FINTANTQUE = 32;
  public static final int SUP = 22;
  public static final int ENTIER = 9;
  public static final int FOIS = 18;
  public static final int FINSI = 29;
  public static final int ECRIRE = 7;
  public static final int EXCLA = 20;
}

